
---
- name: my test play book
  hosts: all
  become: yes

  tasks:
  - name: This is to install multiple packages 
    yum:
      name: [ 'git', 'mysql', 'tree', 'docker', 'wget', 'which' ]
      state: installed
            
