
---
- name: set uo tomcat
  hosts: all
  become: yes

  tasks:
  - name: install java on RedHat 
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
   
  - name: install java on Debian
    yum:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Download tomcat
    get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz  
      dest: /opt

  - name: Exacting tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.72.tar.gz
      dest: /opt
      remote_src: yes


  - name: change permissions
    file:
       path: /opt/apache-tomcat-8.5.72/bin/startup.sh
       mode: 0777
    


  - name: Start tomcat
    shell: nohup ./startup.sh
    args:
       chdir: /opt/apache-tomcat-8.5.72/bin



