
---
- name: my test play book
  hosts: all
  become: yes

  tasks:
  - name: Stoping httpd
    service:
       name: httpd
       state: stopped
      
            

  - name: uninstalling httpd
    yum:
      name: httpd
      state: removed     
